'use strict';
/* Original four-button duels: buffered physical strikes, readable commitments,
   frontal defence and swept projectile contact. No franchise assets are used. */
window.FightMode=(()=>{
 const tau=Math.PI*2;let r=null;const art={};
 const loadingPromise=Promise.all(Object.entries(window.FightSpriteManifest||{}).map(([key,config])=>new Promise(resolve=>{
  const image=new Image(),record={image,config,ready:false,clips:config.frames.map(frame=>{const path=new Path2D();frame.clip.forEach(([x,y],i)=>{x-=frame.anchor[0];y-=frame.anchor[1];if(i)path.lineTo(x,y);else path.moveTo(x,y);});path.closePath();return path;})};art[key]=record;
  image.onload=()=>{record.ready=image.naturalWidth>0;resolve(true);};image.onerror=()=>resolve(false);image.src=config.src;
 })));
 const attacks={punch:{duration:.34,from:.26,to:.55,damage:9},kick:{duration:.49,from:.30,to:.56,damage:14},web:{duration:.72,from:.35,to:.48,damage:4},shuriken:{duration:.77,from:.35,to:.47,damage:10}};
 function enemyKey(){return r?.encounter==='destroyer'&&art.monster?.ready?'monster':'spider';}
 function fighterHeight(f){return r.height*(f.enemy?1.15:1);}
 function attackProgress(f){return f.attack?clamp(1-f.attackT/attacks[f.attack].duration,0,1):0;}
 function attackPhase(f){if(f.windup>0)return 'telegraph';if(!f.attack)return f.stun>0?'hurt':f.guard?'guard':'ready';const t=attackProgress(f),s=attacks[f.attack];return t<s.from?'startup':t<=s.to?'contact':'recovery';}
 function frameFor(f,key=f.enemy?enemyKey():hero){
  const poses=art[key]?.config.poses;if(poses){
   if(f.hp<=0)return {key,i:poses.ko??poses.hurt??11};if(f.stun>0)return {key,i:poses.hurt??11};
   if(f.windup>0)return {key,i:f.next==='web'?poses.web:f.next==='shuriken'?poses.shuriken:f.next==='punch'?poses.punchWindup:poses.kickWindup};
   if(f.attack){const phase=attackPhase(f);if(f.attack==='web')return {key,i:poses.web};if(f.attack==='shuriken')return {key,i:poses.shuriken};return {key,i:f.attack==='punch'?(phase==='startup'?poses.punchWindup:phase==='contact'?poses.punchContact:poses.punchRecover):(phase==='startup'?poses.kickWindup:phase==='contact'?poses.kickContact:poses.kickRecover??poses.idle)};}
   return {key,i:f.guard?poses.guard:f.y<r.ground-3?poses.kickWindup:Math.abs(f.vx)>14?Math.floor(f.walk/Math.PI)%2?poses.walk2:poses.walk1:poses.idle};
  }
  if(f.hp<=0||f.stun>0)return {key,i:7};
  if(f.attack){const t=attackProgress(f),spec=attacks[f.attack],step=t<spec.from*.5?0:t<spec.from?1:t<=spec.to?2:3;
   if(!f.enemy&&art[key+'Attack']?.ready)return {key:key+'Attack',i:(f.attack==='kick'?4:0)+step};
   if(f.enemy&&step===2)return {key,i:f.attack==='punch'||f.attack==='web'||f.attack==='shuriken'?3:f.y<r.ground-3?5:4};
   if(f.enemy&&step<2)return {key,i:f.attack==='kick'?6:0};
  }
  if(f.enemy&&f.windup>0)return {key,i:f.next==='punch'?0:6};
  return {key,i:f.guard?6:f.y<r.ground-3?5:Math.abs(f.vx)>14?1+Math.floor(f.walk/Math.PI)%2:0};
 }
 function poseFrame(f){return frameFor(f).i;}
 function drawAtlas(key,f,height,x=f.x,foot=f.y){const pose=frameFor(f,key),record=art[pose.key];if(!record?.ready)return false;const i=pose.i,frame=record.config.frames[i];if(!frame)return false;const [sx,sy,sw,sh]=frame.rect,[ax,ay]=frame.anchor,scale=height/record.config.commonHeight;
  const moving=Math.abs(f.vx)>14&&!f.attack&&!f.guard,bob=moving?Math.sin(f.walk*2)*height*.007:0,fall=f.hp<=0&&r.between?journeyEase(clamp((r.resultAge-.1)/.6,0,1)):0;
  ctx.save();ctx.translate(x,foot+bob-fall*height*.19);if(fall)ctx.rotate(-f.face*fall*Math.PI*.42);ctx.scale(f.face*scale,scale);const breath=f.attack||moving||f.hp<=0?1:1+Math.sin(r.elapsed*2.2)*.005;ctx.scale(1,breath);ctx.clip(record.clips[i]);ctx.drawImage(record.image,sx,sy,sw,sh,sx-ax,sy-ay,sw,sh);ctx.restore();return true;
 }
 function dims(){const d=ModeFX.measure();d.ground=d.h-clamp(d.h*.085,24,58);d.height=Math.min(d.w*.335,clamp((d.ground-d.top-34)*.52,56,182));d.unit=d.height/104;return d;}
 function fighter(x,face,enemy=false){return {x,y:r.ground,vx:0,vy:0,face,hp:100,attack:null,attackT:0,attackHit:false,launched:false,stun:0,inv:0,guard:false,guardAge:10,walk:0,enemy,windup:0,windupDuration:0,next:'punch',ai:1.1,attackIndex:0,combo:0,comboLife:0,lastHit:null,comboAttack:false,counter:0,dash:0,pressure:0,pressureLife:0,escapeQueued:false,escapeCD:0,evade:0,evadeDirection:0,forcedSpecial:null,rangedCounter:0};}
 function setup(retry=false){const d=dims();Object.assign(r,d);r.p=fighter(d.w*.31,1);r.e=fighter(d.w*.69,-1,true);r.timer=99;r.elapsed=0;r.intro=retry?1.6:r.round===1?(r.encounter==='destroyer'?3.4:2.8):2.5;r.introDuration=r.intro;r.freeze=0;r.effects=[];r.texts=[];r.projectiles=[];r.tether=null;r.webImmune=0;r.shake=0;r.flash=0;r.between=0;r.result=null;r.resultAge=0;r.request={jump:0};r.buffer=null;r.lastAxis=0;r.lastGuardInput=false;r.guardPressAge=10;r.tapDirection=0;r.tapAge=10;r.comboDisplay=0;r.entryScore=score;clearInput();}
 function start(options={}){const encounter=options.encounter==='destroyer'?'destroyer':'dojo';r={encounter,destination:options.destination||(encounter==='destroyer'?{type:'rescue'}:{type:'level',stage:3}),round:1,wins:0,serial:0,stats:{hits:0,comboHits:0,parries:0,webShots:0,webHits:0,webMisses:0,pulls:0,webEscapes:0,webBlocks:0,shurikens:0,projectileBlocks:0,evades:0}};setup();}
 function resize(){if(!r)return;const d=dims(),sx=d.w/r.w,su=d.unit/r.unit;for(const f of [r.p,r.e]){f.x*=sx;f.y=d.ground-(r.ground-f.y)*su;f.vx*=su;f.vy*=su;}for(const q of r.projectiles){q.x*=sx;q.y=d.ground-(r.ground-q.y)*su;q.vx*=su;q.vy*=su;q.radius*=su;}Object.assign(r,d);sync();}
 function press(action){if(!r||r.intro>0||r.between)return;if(r.tether&&['punch','kick','jump'].includes(action)){r.tether.breaks++;burstAt(r.p.x,r.p.y-r.height*.52,'#c5efff',6);if(r.tether.breaks>=r.tether.required)breakTether(true);return;}if(action==='jump')r.request.jump=.20;else if(attacks[action]&&['punch','kick'].includes(action))r.buffer={type:action,life:.32};}
 function rectHits(a,b){return Math.abs(a.x-b.x)<(a.w+b.w)*.5&&Math.abs(a.y-b.y)<(a.h+b.h)*.5;}
 function sweptRectHit(ax,ay,bx,by,box,rad){const dx=bx-ax,dy=by-ay,minX=box.x-box.w*.5-rad,maxX=box.x+box.w*.5+rad,minY=box.y-box.h*.5-rad,maxY=box.y+box.h*.5+rad;let lo=0,hi=1;for(const [p,v,mn,mx] of [[ax,dx,minX,maxX],[ay,dy,minY,maxY]]){if(Math.abs(v)<.00001){if(p<mn||p>mx)return false;}else{let a=(mn-p)/v,b=(mx-p)/v;if(a>b)[a,b]=[b,a];lo=Math.max(lo,a);hi=Math.min(hi,b);if(lo>hi)return false;}}return true;}
 function hurtbox(f){const h=fighterHeight(f);return {x:f.x,y:f.y-h*(f.guard?.44:.52),w:h*.34,h:h*(f.guard?.78:.91)};}
 function hitboxes(f){if(!f.attack||f.stun>0||!['punch','kick'].includes(f.attack))return [];const pose=frameFor(f),cfg=art[pose.key]?.config,frame=cfg?.frames[pose.i];if(!frame)return [];const contacts=frame.contacts||(frame.contact?[frame.contact]:[]),scale=fighterHeight(f)/cfg.commonHeight;return contacts.map(c=>({x:f.x+f.face*c[0]*scale,y:f.y+c[1]*scale,w:c[2]*scale,h:c[3]*scale}));}
 function hitbox(f){return hitboxes(f)[0]||null;}
 function strike(f,type,combo=false){if(f.attack||f.stun>0||f.windup>0||!attacks[type])return false;f.guard=false;f.guardAge=10;f.attack=type;f.attackT=attacks[type].duration;f.attackHit=false;f.launched=false;f.comboAttack=combo;f.vx=f.face*(type==='kick'?22:35)*r.unit;tone(type==='kick'?160:type==='punch'?270:390,.05);return true;}
 function jump(f){if(f.y>=r.ground-.1&&f.stun<=0&&!f.attack){const maxHeight=Math.max(22,Math.min(132*r.unit,r.ground-r.top-fighterHeight(f)*.96-10));f.guard=false;f.guardAge=10;f.vy=-Math.sqrt(2*1300*r.unit*maxHeight);tone(350,.07);return true;}return false;}
 function burstAt(x,y,color,count=16){for(let i=0;i<count;i++){const a=Math.random()*tau,v=(65+Math.random()*170)*r.unit;r.effects.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.3+Math.random()*.25,color});}if(r.effects.length>180)r.effects.splice(0,r.effects.length-180);}
 function floating(f,text,color='#fff0cd'){r.texts.push({x:f.x,y:f.y-fighterHeight(f)*1.1,life:.72,text,color});}
 function facingGuard(f,sourceFace){return f.guard&&f.face===-sourceFace&&f.y>=r.ground-.1;}
 function parry(a,b,x,y){b.counter=.9;b.inv=.2;b.stun=0;a.attack=null;a.windup=0;a.stun=.34;a.vx=-a.face*105*r.unit;a.ai=Math.max(a.ai,.5);r.stats.parries++;r.freeze=.065;r.shake=2.5;r.flash=.09;burstAt(x,y,'#b8f6f3',22);floating(b,'PARRY!','#b8f6f3');window.GameAudio?.strike?.('punch',true,true);tone(650,.12);}
 function damage(a,b){const box=hitboxes(a).find(box=>rectHits(box,hurtbox(b)));if(a.attackHit||b.inv>0||!box)return;a.attackHit=true;const castingGuard=b.enemy&&b.face===-a.face&&((b.windup>0&&['web','shuriken'].includes(b.next))||(b.attack&&['web','shuriken'].includes(b.attack)&&!b.launched))&&a.counter<=0&&!(a.attack==='kick'&&a.y<r.ground-r.height*.12),blocked=facingGuard(b,a.face)||castingGuard;if(blocked&&!b.enemy&&b.guardAge<=.17){parry(a,b,box.x,box.y);return;}
  const counter=a.counter>0,combo=a.comboAttack&&!blocked,base=attacks[a.attack].damage,dmg=blocked?(a.attack==='kick'?2:1):base+(combo?3:0)+(counter?4:0);b.hp=Math.max(0,b.hp-dmg);b.stun=castingGuard?0:blocked?.10:a.attack==='kick'?.29:.22;b.inv=blocked?.12:.18;if(!castingGuard){b.attack=null;b.windup=0;}b.guard=false;b.vx=castingGuard?0:a.face*(blocked?70:a.attack==='kick'?170:80)*r.unit;if(!blocked)b.vy=-(a.attack==='kick'?95:32)*r.unit;r.freeze=blocked?.033:a.attack==='kick'?.075:.048;r.shake=blocked?1.5:a.attack==='kick'?5:3.2;
  if(b.enemy&&!blocked){b.pressure=b.pressureLife>0?b.pressure+1:1;b.pressureLife=1.5;if(b.pressure>=3&&b.escapeCD<=0)b.escapeQueued=true;}
  if(!a.enemy&&!blocked){r.stats.hits++;a.combo=a.comboLife>0?a.combo+1:1;a.comboLife=1.12;a.lastHit=a.attack;r.comboDisplay=a.combo;if(a.combo>1)r.stats.comboHits++;a.counter=0;}else if(blocked)a.combo=0;
  burstAt(box.x,box.y,blocked?'#9fd7ff':counter?'#b7fff0':'#f3d6a1',blocked?10:20);floating(b,castingGuard?'CAST GUARD':blocked?'GUARD':counter?`COUNTER −${dmg}`:`−${dmg}`,blocked?'#b9e4ff':counter?'#b7fff0':'#fff0cd');window.GameAudio?.strike?.(a.attack,blocked,false);tone(blocked?480:a.attack==='kick'?95:125,.1);
 }
 function launchProjectile(f,type){const h=fighterHeight(f),pose=frameFor(f),config=art[pose.key]?.config,cast=config?.frames[pose.i]?.cast,scale=h/(config?.commonHeight||104),originX=f.x+f.face*(cast?cast[0]*scale:h*.38),originY=f.y+(cast?cast[1]*scale:-h*(type==='web'?.56:.58)),speed=(type==='web'?260:325)*r.unit,targetY=r.ground-r.height*.52,targetX=f.targetX??(f.enemy?r.p.x:r.e.x),q={id:++r.serial,type,owner:f.enemy?'e':'p',x:originX,y:originY,vx:f.face*speed,vy:clamp((targetY-originY)/Math.max(r.height*.7,Math.abs(targetX-originX))*speed,-speed*.3,speed*.3),radius:(type==='web'?7:9)*r.unit,life:3.8,angle:0,face:f.face};r.projectiles.push(q);if(type==='web')r.stats.webShots++;if(type==='shuriken'){r.stats.shurikens++;if(r.encounter==='destroyer'&&r.round===2){r.projectiles.push({...q,id:++r.serial,x:q.x-f.face*52*r.unit,y:f.y-h*.30,life:4.0,angle:1.2});r.stats.shurikens++;}}tone(type==='web'?500:740,.09);return q;}
 function breakTether(escaped=false){if(!r.tether)return;const p=r.p;r.tether=null;r.webImmune=Math.max(r.webImmune,2.5);p.stun=0;p.inv=.65;p.vx=(p.x<r.e.x?-1:1)*125*r.unit;r.e.ai=Math.max(r.e.ai,.8);if(escaped){r.stats.webEscapes++;p.counter=.9;r.e.stun=.32;floating(p,'WEB CUT!','#c9f5ff');burstAt(p.x,p.y-r.height*.55,'#c9f5ff',24);tone(680,.13);}else floating(p,'FREE!','#c9f5ff');}
 function updateTether(dt){if(!r.tether)return;const t=r.tether,p=r.p,e=r.e;t.age+=dt;t.life-=dt;e.vx=approach(e.vx,0,25,dt);e.attack=null;e.windup=0;e.ai=Math.max(e.ai,.65);p.guard=false;p.attack=null;if(t.age>.15){const destination=e.x+(p.x<e.x?-1:1)*r.height*.70,distance=destination-p.x;if(Math.abs(distance)>r.unit*8){p.vx=clamp(distance*5,-210*r.unit,210*r.unit);if(!t.pulling){t.pulling=true;r.stats.pulls++;}}else p.vx=0;}if(t.life<=0)breakTether(false);}
 function updateProjectiles(dt){for(const q of r.projectiles){if(q.dead)continue;const oldX=q.x,oldY=q.y;q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;q.angle+=dt*(q.type==='web'?5:17);const target=q.owner==='e'?r.p:r.e;
   if(q.owner==='e'&&r.p.attack&&attackPhase(r.p)==='contact'&&hitboxes(r.p).some(b=>sweptRectHit(oldX,oldY,q.x,q.y,b,q.radius))){q.dead=true;burstAt(q.x,q.y,q.type==='web'?'#daf0ff':'#cbff95',12);floating(r.p,q.type==='web'?'WEB CUT':'STAR CUT','#ccf5cf');if(q.type==='web')r.stats.webBlocks++;continue;}
   if(sweptRectHit(oldX,oldY,q.x,q.y,hurtbox(target),q.radius)){
    const blocked=facingGuard(target,Math.sign(q.vx));if(blocked){if(!target.enemy&&target.guardAge<=.17){q.owner='p';q.vx=-q.vx*1.15;q.vy=-q.vy*1.15;q.face=-q.face;q.x=target.x+target.face*r.height*.35;target.counter=.8;r.stats.parries++;r.flash=.08;floating(target,'REFLECT!','#bdfff1');burstAt(q.x,q.y,'#bdfff1',20);tone(680,.1);continue;}q.dead=true;target.stun=.08;target.hp=Math.max(0,target.hp-(q.type==='web'?0:1));r.stats.projectileBlocks++;if(q.type==='web')r.stats.webBlocks++;burstAt(q.x,q.y,'#bddeff',12);floating(target,'GUARD','#bddeff');tone(460,.08);continue;}
    q.dead=true;if(target.inv>0)continue;if(q.type==='web'&&q.owner==='e'){if(r.webImmune>0||r.tether)continue;r.tether={age:0,life:1.5,breaks:0,required:3,source:'e',pulling:false,hitX:q.x,hitY:q.y};r.webImmune=3.6;r.stats.webHits++;target.hp=Math.max(0,target.hp-4);target.stun=.16;target.inv=.25;target.attack=null;r.e.ai=1.5;r.e.windup=0;r.freeze=.045;burstAt(q.x,q.y,'#dcecff',20);tone(210,.12);}else{const dmg=q.owner==='p'?11:10;target.hp=Math.max(0,target.hp-dmg);target.stun=.25;target.inv=.45;target.attack=null;target.windup=0;target.guard=false;target.vx=Math.sign(q.vx)*130*r.unit;r.shake=4;r.freeze=.06;burstAt(q.x,q.y,'#c7ffa0',20);floating(target,`−${dmg}`,'#d6ffa7');tone(150,.1);}continue;
   }
   if(q.life<=0||q.x<-q.radius*3||q.x>r.w+q.radius*3){q.dead=true;if(q.type==='web'&&q.owner==='e')r.stats.webMisses++;}
  }r.projectiles=r.projectiles.filter(q=>!q.dead);
 }
 function physics(f,dt){f.stun=Math.max(0,f.stun-dt);f.inv=Math.max(0,f.inv-dt);f.counter=Math.max(0,f.counter-dt);f.comboLife=Math.max(0,f.comboLife-dt);if(f.comboLife<=0)f.combo=0;f.dash=Math.max(0,f.dash-dt);f.escapeCD=Math.max(0,f.escapeCD-dt);f.pressureLife=Math.max(0,f.pressureLife-dt);if(f.pressureLife<=0)f.pressure=0;if(f.attack){f.attackT-=dt;if(['web','shuriken'].includes(f.attack)&&!f.launched&&attackProgress(f)>=attacks[f.attack].from){f.launched=true;launchProjectile(f,f.attack);}if(f.attackT<=0)f.attack=null;}
  f.vy+=1300*r.unit*dt;f.y+=f.vy*dt;if(f.y>=r.ground){if(f.vy>300*r.unit)burstAt(f.x,r.ground,'#bdc8e5',9);f.y=r.ground;f.vy=0;}f.x=clamp(f.x+f.vx*dt,r.height*.39,r.w-r.height*.39);f.walk+=Math.abs(f.vx)*dt*.04/r.unit;f.vx*=Math.exp(-dt*(f.dash>0?1.2:7.6));
 }
 function cpu(dt){const f=r.e,p=r.p,dist=Math.abs(f.x-p.x),range=r.height*.69;
  if(f.escapeQueued&&f.escapeCD<=0&&!r.tether){f.escapeQueued=false;f.escapeCD=5;f.pressure=0;f.stun=0;f.attack=null;f.windup=0;f.guard=false;let away=Math.sign(f.x-p.x)||-f.face;if(f.x+away*r.height*1.45<r.height*.40||f.x+away*r.height*1.45>r.w-r.height*.40)away*=-1;f.evadeDirection=away;f.face=away;f.evade=.34;f.inv=.42;f.vx=away*320*r.unit;const hop=Math.max(12,Math.min(38*r.unit,r.ground-r.top-fighterHeight(f)-8));f.vy=-Math.sqrt(2*1300*r.unit*hop);f.next='backstep';f.forcedSpecial=f.rangedCounter++%2?'shuriken':'web';f.ai=0;r.stats.evades++;floating(f,'BACKSTEP!','#c9e2ff');burstAt(f.x,f.y-r.height*.16,'#a9c9ee',10);}
  if(f.evade>0){f.evade=Math.max(0,f.evade-dt);f.vx=f.evadeDirection*320*r.unit;return;}
  if(f.forcedSpecial&&f.y<r.ground-.5){f.vx=approach(f.vx,0,22,dt);return;}
  if(!f.attack&&!f.windup)f.face=p.x>f.x?1:-1;if(f.stun>0||r.tether){f.windup=0;return;}
  if(f.windup>0){f.vx=approach(f.vx,0,25,dt);f.windup-=dt;if(f.windup<=0){f.windup=0;if(f.next==='leap'){jump(f);strike(f,'kick');f.vx=f.face*220*r.unit;}else strike(f,f.next);f.ai=(r.encounter==='destroyer'?r.round===2?.68:.85:r.round===2?.82:1.0);}return;}
  if(f.attack)return;f.ai-=dt;f.guard=!!p.attack&&dist<range&&attackProgress(p)>.12&&f.ai>.25&&f.attackIndex%4===2;
  const patterns=r.encounter==='destroyer'?(r.round===2?['web','shuriken','leap','punch','kick','shuriken','web','leap']:['web','punch','shuriken','kick','leap','punch']):(r.round===2?['punch','kick','web','leap','shuriken','kick']:['punch','kick','punch','web','kick']);
  let next=f.forcedSpecial||patterns[f.attackIndex%patterns.length],ranged=next==='web'||next==='shuriken';if(ranged&&dist<r.height*.47){next='punch';ranged=false;}
  if(!f.guard&&dist>(ranged?r.height*1.65:range*.85))f.vx=f.face*(r.encounter==='destroyer'?145:130)*r.unit;else if(dist<r.height*(ranged?1.1:.47))f.vx=-f.face*(ranged?135:65)*r.unit;else f.vx=approach(f.vx,0,22,dt);
  if(f.ai<=0&&!f.guard&&((ranged&&dist>=r.height*.48&&dist<r.height*4.8)||(!ranged&&dist<range))){f.next=next;f.forcedSpecial=null;f.attackIndex++;f.windupDuration=next==='web'?.82:next==='shuriken'?.70:next==='leap'?.68:r.round===2?.44:.54;f.windup=f.windupDuration;f.guard=false;f.vx=0;f.targetX=p.x;}
 }
 function sync(){if(r)ModeFX.sync(r.p.x,r.p.y-r.height*.5,r.height,Math.ceil(r.p.hp/100*3));}
 function finish(){if(r.between)return;const won=r.e.hp<=0&&r.p.hp>0;r.result=won?'win':'retry';r.between=won?3.2:2.8;r.resultAge=0;r.p.attack=r.e.attack=null;r.e.windup=0;r.projectiles=[];r.tether=null;clearInput();if(won){r.wins++;score+=r.encounter==='destroyer'?100:60;burstAt(r.e.x,r.e.y-r.height*.65,'#bd9df3',30);window.GameAudio?.victory?.();}else tone(120,.2);}
 function update(dt){if(!r)return;r.elapsed+=dt;r.shake=Math.max(0,r.shake-dt*22);r.flash=Math.max(0,r.flash-dt);r.webImmune=Math.max(0,r.webImmune-dt);for(const e of r.effects){e.x+=e.vx*dt;e.y+=e.vy*dt;e.vy+=280*r.unit*dt;e.life-=dt;}r.effects=r.effects.filter(e=>e.life>0);for(const t of r.texts){t.y-=22*dt;t.life-=dt;}r.texts=r.texts.filter(t=>t.life>0);
  if(r.intro>0){r.intro=Math.max(0,r.intro-dt);sync();return;}
  if(r.between>0){r.between-=dt;r.resultAge+=dt;if(r.between<=0){if(r.result==='win'){if(r.wins>=2){beginTransition(r.destination);return;}r.round=2;setup();}else{score=r.entryScore;setup(true);}}return;}
  if(r.freeze>0){r.freeze=Math.max(0,r.freeze-dt);return;}
  r.timer=Math.max(0,r.timer-dt);const p=r.p,holdingGuard=!!(input.guard||input.down||keys.has('KeyL')||keys.has('ArrowDown')||keys.has('KeyS'));if(holdingGuard&&!r.lastGuardInput)r.guardPressAge=0;else if(holdingGuard)r.guardPressAge+=dt;else r.guardPressAge=10;r.lastGuardInput=holdingGuard;p.guardAge=r.guardPressAge;if(!p.attack&&!r.tether)p.face=r.e.x>p.x?1:-1;
  r.request.jump=Math.max(0,r.request.jump-dt);r.tapAge+=dt;if(r.buffer){r.buffer.life-=dt;if(r.buffer.life<=0)r.buffer=null;}
  if(p.stun<=0&&!r.tether){const axis=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0)||input.axis;
   const guard=holdingGuard&&p.y>=r.ground-.1&&!p.attack;p.guard=guard;
   const direction=Math.abs(axis)>.7?Math.sign(axis):0;if(direction&&r.lastAxis===0&&!p.guard&&!p.attack){if(r.tapDirection===direction&&r.tapAge<.26){p.dash=.16;p.vx=direction*420*r.unit;burstAt(p.x,p.y-r.height*.18,'#b4d9f3',6);}r.tapDirection=direction;r.tapAge=0;}r.lastAxis=direction;
   if(!p.attack&&!p.guard&&p.dash<=0)p.vx=approach(p.vx,axis*225*r.unit,28,dt);else if(p.guard)p.vx=approach(p.vx,axis*55*r.unit,25,dt);else if(p.dash<=0)p.vx=approach(p.vx,0,22,dt);
   if(r.request.jump&&jump(p)){r.request.jump=0;p.vx+=axis*95*r.unit;}
   if(!p.guard&&r.buffer){if(p.attack&&p.attackHit&&attackProgress(p)>attacks[p.attack].to&&r.buffer.type!==p.attack){p.attack=null;const type=r.buffer.type;if(strike(p,type,true))r.buffer=null;}else if(!p.attack&&strike(p,r.buffer.type,p.comboLife>0&&p.lastHit!==r.buffer.type))r.buffer=null;}
  }else if(!r.tether){p.guard=false;}
  cpu(dt);updateTether(dt);physics(p,dt);physics(r.e,dt);for(const [a,b] of [[p,r.e],[r.e,p]])if(a.attack&&['punch','kick'].includes(a.attack)){const t=attackProgress(a),spec=attacks[a.attack];if(t>=spec.from&&t<=spec.to)damage(a,b);}updateProjectiles(dt);
  const distance=p.x-r.e.x,min=r.height*.43;if(Math.abs(distance)<min&&Math.abs(p.y-r.e.y)<r.height*.7){const sign=distance<0?-1:1,mid=(p.x+r.e.x)/2;p.x=clamp(mid+sign*min*.5,r.height*.39,r.w-r.height*.39);r.e.x=clamp(mid-sign*min*.5,r.height*.39,r.w-r.height*.39);}
  sync();if(p.hp<=0||r.e.hp<=0||r.timer<=0)finish();
 }
 function scenery(d){const sky=ctx.createLinearGradient(0,0,0,d.h);sky.addColorStop(0,'#10142e');sky.addColorStop(.6,'#333055');sky.addColorStop(1,'#60445d');ctx.fillStyle=sky;ctx.fillRect(0,0,d.w,d.h);glow(d.w*.72,d.top+(d.h-d.top)*.28,d.h*.4,'#a893e029');
  const mx=d.w*.72,my=d.top+(d.h-d.top)*.24,mr=Math.min(51,d.w*.07),moon=ctx.createRadialGradient(mx-mr*.3,my-mr*.4,1,mx,my,mr);moon.addColorStop(0,'#dccfdf9c');moon.addColorStop(.6,'#b4abc67a');moon.addColorStop(1,'#7773994d');circle(mx,my,mr,moon);for(let i=0;i<6;i++)waCrater(mx+(noise(i+872)-.5)*mr*1.2,my+(noise(i+863)-.5)*mr*1.2,mr*(.06+noise(i+831)*.1),mr*.055);ctx.strokeStyle='#a8b8d12c';ctx.lineWidth=1;
  for(let i=0;i<45;i++){const x=noise(i+832)*d.w,y=d.top+noise(i+538)*(r.ground-d.top);circle(x,y,1,'#e1d4f84d');}
  waDistantTemple(d.w*.22,r.ground,r.height*2.9,r.height*2.8,2);waDistantTemple(d.w*.85,r.ground,r.height*2.2,r.height*2.2,4);
  const shrineScale=clamp((d.h-d.top)/430,.28,1.5);waRuin(d.w*.5,r.ground,shrineScale,2,false);
  for(const side of [.02,.98])waRuin(d.w*side,r.ground,shrineScale*.7,1,true);
  const mist=ctx.createLinearGradient(0,r.ground-r.height*1.7,0,r.ground);mist.addColorStop(0,'#a6aad800');mist.addColorStop(.55,'#a6aad810');mist.addColorStop(1,'#aaaadc35');ctx.fillStyle=mist;ctx.fillRect(0,r.ground-r.height*1.7,d.w,r.height*1.7);
  const mid=d.w/2,y=r.ground-r.height*1.45;ctx.strokeStyle='#c1b1dd44';ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(mid,y,r.height*.72,r.height*.93,0,0,tau);ctx.stroke();for(let i=0;i<8;i++){const a=i*tau/8+r.elapsed*.05;star(mid+Math.cos(a)*r.height*.72,y+Math.sin(a)*r.height*.93,2,'#d8c6efa0');}
  const ground=ctx.createLinearGradient(0,r.ground,0,d.h);ground.addColorStop(0,'#4f506e');ground.addColorStop(1,'#1c2138');ctx.fillStyle=ground;ctx.fillRect(0,r.ground,d.w,d.h-r.ground);line(0,r.ground,d.w,r.ground,'#d2c5e3',1.5);for(let i=0;i<9;i++)line(i*d.w/8,r.ground,i*d.w/8+(i-4)*12,d.h,'#c7b8d323',1);
  // Silken pennants and lanterns move from fixed anchors instead of looking
  // like broken trees along the edge of the scene.
  for(const side of [.12,.88]){const x=d.w*side,y=d.top+22;line(x,d.top,x,y,'#dac8e667',1);glow(x,y+6,26,'#dcc0f529');rounded(x-7,y,14,21,5,'#9d75b780');line(x-5,y+19,x+5,y+19,'#e2c7da',1);}
  ctx.strokeStyle='#c5b1df23';ctx.lineWidth=.65;const silkY=d.top+10;
  for(const side of [0,1]){const sx=d.w*side;for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(sx,silkY);ctx.quadraticCurveTo(sx+(side?-1:1)*i*18,silkY+40,sx+(side?-1:1)*i*28,silkY+75);ctx.stroke();}}
 }
 function limb(points,width,color,shine){ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#0b1024';ctx.lineWidth=width+3;ctx.beginPath();ctx.moveTo(...points[0]);for(const p of points.slice(1))ctx.lineTo(...p);ctx.stroke();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();if(shine){ctx.strokeStyle=shine;ctx.lineWidth=Math.max(1,width*.17);ctx.stroke();}}
 function fallbackNinja(f){
  if(art.spider?.ready){
   ellipse(f.x,r.ground+3,r.height*.41,r.height*.055,'#0710216b');glow(f.x,f.y-r.height*.65,r.height*.72,f.windup>0?'#c1f99626':'#aa7bda16');
   ctx.save();ctx.translate(f.x,f.y);ctx.scale(f.face,1);if(f.inv>0)ctx.globalAlpha=.74+Math.sin(r.elapsed*38)*.2;
   // drawAtlas owns the frame scale; this wrapper only adds damage flash.
   ctx.restore();ctx.save();if(f.inv>0)ctx.globalAlpha=.74+Math.sin(r.elapsed*38)*.2;drawAtlas('spider',f,r.height*1.16);ctx.restore();
   if(f.windup>0){ctx.strokeStyle='#c9f9a280';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(f.x,f.y-r.height*.64,r.height*.58,-Math.PI/2,-Math.PI/2+(1-f.windup/.7)*tau);ctx.stroke();}
   return;
  }
  const h=r.height*1.16,k=h/104,phase=f.walk,t=f.attack?(f.attack==='kick'?(.48-f.attackT)/.48:(.32-f.attackT)/.32):0,extend=Math.sin(Math.PI*clamp(t*1.45,0,1)),air=f.y<r.ground-.1;
  ellipse(f.x,r.ground+3,h*.39,h*.055,'#0710216b');ctx.save();ctx.translate(f.x,f.y);ctx.scale(f.face*k,k);if(f.inv>0)ctx.globalAlpha=.75+Math.sin(r.elapsed*40)*.2;
  glow(0,-65,56,f.windup>0?'#c9fd9e33':'#9064c526');const gait=Math.sin(phase)*8,cloak=Math.sin(r.elapsed*4)*3+Math.abs(f.vx)*.015;
  // Four articulated arms, a chitin hood, jade eyes and a streaming sash.
  for(const side of [-1,1])for(let pair=0;pair<2;pair++){const far=side<0,sy=-70+pair*21,attack=side>0&&f.attack==='punch',reach=attack?extend*(pair===0?58:35):0,bob=Math.sin(r.elapsed*2.7+pair)*2;
   ctx.save();if(far)ctx.globalAlpha*=.7;limb([[side*12,sy],[side*(29+reach*.5),sy+12-bob],[side*(22+reach),sy+5-pair*2]],9-pair,'#3c3a61','#af9bd770');ellipse(side*(22+reach),sy+5-pair*2,7,6,'#65557d');for(let i=0;i<3;i++)line(side*(25+reach),sy+2+i*3,side*(32+reach),sy+1+i*3,'#c9dda8',1.5);ctx.restore();}
  const kick=f.attack==='kick'?extend*50:0;limb([[-8,-33],[-12-gait*.5,-18],[-17-gait,-3]],12,'#2a2d4d','#7f739967');limb([[10,-33],[18+gait*.5+kick*.4,-20-kick*.45],[21+gait+kick,-4-kick*.63]],13,'#353652','#a498b95a');ellipse(-18-gait,-3,11,4,'#505376');ellipse(24+gait+kick,-4-kick*.63,11,4,'#73718d');
  const armor=ctx.createLinearGradient(-20,-78,25,-27);armor.addColorStop(0,'#86719b');armor.addColorStop(.5,'#393950');armor.addColorStop(1,'#151c32');ctx.fillStyle=armor;ctx.strokeStyle='#b5a2c478';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-15,-77);ctx.quadraticCurveTo(3,-88,20,-71);ctx.lineTo(17,-35);ctx.quadraticCurveTo(2,-24,-15,-36);ctx.closePath();ctx.fill();ctx.stroke();for(let i=0;i<3;i++)line(-11,-63+i*9,14,-63+i*9,'#b6a5d254',1);
  rounded(-18,-39,38,7,2,'#82739d');ctx.fillStyle='#ad9dd5';ctx.beginPath();ctx.moveTo(-13,-37);ctx.bezierCurveTo(-37-cloak,-43,-32-cloak,-20,-46-cloak,-25);ctx.lineTo(-38-cloak,-15);ctx.bezierCurveTo(-20,-18,-26,-31,-10,-31);ctx.fill();
  ctx.fillStyle='#252842';ctx.strokeStyle='#9b8fbd';ctx.lineWidth=1.1;ctx.beginPath();ctx.moveTo(-14,-77);ctx.quadraticCurveTo(-27,-97,-7,-106);ctx.lineTo(5,-113);ctx.quadraticCurveTo(25,-104,25,-85);ctx.quadraticCurveTo(13,-74,-14,-77);ctx.fill();ctx.stroke();ellipse(7,-91,16,11,'#101b2b');for(let i=0;i<3;i++){ellipse(4+i*7,-96+i*4,3,1.9,f.windup>0?'#ebffc0':'#a2df9d');}line(17,-84,23,-79,'#d5d3aa',2);line(11,-82,16,-76,'#c3c7aa',2);
  if(air){ctx.strokeStyle='#b5a2dc8a';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-35,-85);ctx.quadraticCurveTo(-44,-122,0,-135);ctx.stroke();}
  if(f.windup>0){ctx.strokeStyle='#cafd9a';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,-64,40,-Math.PI/2,-Math.PI/2+(1-f.windup/.7)*tau);ctx.stroke();}
  ctx.restore();
 }
 function destroyedScenery(d){
  const g=ctx.createLinearGradient(0,d.top,0,d.h);g.addColorStop(0,'#10122e');g.addColorStop(.55,'#332a4a');g.addColorStop(1,'#40252c');ctx.fillStyle=g;ctx.fillRect(0,0,d.w,d.h);glow(d.w*.42,d.top+(r.ground-d.top)*.40,d.w*.55,'#907cba20');glow(d.w*.78,r.ground,r.height*2.5,'#ffb26a16');
  for(let i=0;i<85;i++){const x=noise(i+70)*d.w,y=d.top+noise(i+411)*(r.ground-d.top);circle(x,y,.5+noise(i+231)*1.1,`rgba(216,219,243,${.2+noise(i+197)*.42})`);}
  const starX=d.w*.21,starY=d.top+(r.ground-d.top)*.32;ctx.save();ctx.globalAlpha=.28;waConsumedStar(starX,starY,Math.min(d.w*.055,(r.ground-d.top)*.11));ctx.restore();
  for(let i=0;i<5;i++){const x=noise(i+130)*d.w,y=d.top+noise(i+191)*(r.ground-d.top)*.7;ctx.save();ctx.globalAlpha=.22;waAsteroid(x,y,r.height*(.12+noise(i+125)*.14),r.height*.13,53+i,false);ctx.restore();}
  const wall=r.ground-r.height*.8;ctx.fillStyle='#1a1c3080';ctx.beginPath();ctx.moveTo(0,r.ground);for(let i=0;i<=18;i++){const x=i*d.w/18,y=wall+noise(i+953)*r.height*.34;ctx.lineTo(x,y);}ctx.lineTo(d.w,r.ground);ctx.fill();
  const floor=ctx.createLinearGradient(0,r.ground,0,d.h);floor.addColorStop(0,'#5d576c');floor.addColorStop(1,'#151b2b');ctx.fillStyle=floor;ctx.fillRect(0,r.ground,d.w,d.h-r.ground);line(0,r.ground,d.w,r.ground,'#b9bccd',1.7);
  for(let i=0;i<11;i++){const x=noise(i+877)*d.w;line(x,r.ground,x+25*r.unit,r.h,'#b8c3d22c',1);}for(let i=0;i<5;i++){const x=noise(i+257)*d.w,y=r.ground+6+noise(i+765)*Math.max(1,d.h-r.ground-12);line(x,y,x+28*r.unit,y+4*r.unit,'#e3aa674d',1);}
  ctx.strokeStyle='#b8cbef1d';ctx.lineWidth=1;for(let side=0;side<2;side++){const x=side*d.w,y=d.top+22;for(let i=0;i<6;i++){ctx.beginPath();ctx.moveTo(x,y);ctx.quadraticCurveTo(x+(side?-1:1)*(40+i*15)*r.unit,y+40*r.unit,x+(side?-1:1)*(50+i*23)*r.unit,y+(70+i*8)*r.unit);ctx.stroke();}}
 }
 function ninja(f){const key=enemyKey(),h=fighterHeight(f);if(!art[key]?.ready){fallbackNinja(f);return;}ellipse(f.x,r.ground+3,h*.35,h*.052,'#060a176d');glow(f.x,f.y-h*.57,h*.62,f.windup>0?(f.next==='web'?'#c9eaff2d':'#c1f99621'):'#9f7ad512');ctx.save();if(f.inv>0)ctx.globalAlpha=.74+Math.sin(r.elapsed*38)*.2;
  if(r.encounter==='destroyer'&&r.intro>0&&r.round===1){const age=r.introDuration-r.intro,form=journeyEase(clamp(age/1.2,0,1));ctx.save();ctx.translate(f.x,f.y);ctx.scale(.78+form*.22,.46+form*.54);ctx.translate(-f.x,-f.y);drawAtlas(key,f,h);ctx.restore();if(form<1){const rr=h*(.4+form*.1);ctx.strokeStyle='#c8bde57d';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(f.x,f.y-h*.48,rr,rr*.8,0,0,tau);ctx.stroke();for(let i=0;i<8;i++){const a=i*tau/8+age;star(f.x+Math.cos(a)*rr,f.y-h*.48+Math.sin(a)*rr*.8,2,'#dceace');}}}else drawAtlas(key,f,h);ctx.restore();
  if((f.windup>0&&['web','shuriken'].includes(f.next))||(f.attack&&['web','shuriken'].includes(f.attack)&&!f.launched)){ctx.strokeStyle='#bce6ea77';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(f.x+f.face*h*.20,f.y-h*.54,h*.16,h*.40,0,-Math.PI*.5,Math.PI*.5);ctx.stroke();}
  if(f.windup>0){const a=1-f.windup/f.windupDuration;ctx.strokeStyle=f.next==='web'?'#c8eaff9c':'#d8ee9d9c';ctx.lineWidth=2;ctx.beginPath();ctx.arc(f.x,f.y-h*.57,h*.57,-Math.PI/2,-Math.PI/2+a*tau);ctx.stroke();if(f.next==='leap'){ctx.strokeStyle='#d9b2f387';ctx.setLineDash([4,5]);ctx.beginPath();ctx.ellipse(clamp(f.targetX,h*.3,r.w-h*.3),r.ground, r.height*.3,6*r.unit,0,0,tau);ctx.stroke();ctx.setLineDash([]);}}
 }
 function heroFighter(f){const h=r.height,j=ModeFX.exitPose(f.x,f.y,h);let introY=0,spin=0;if(r.intro>0){const a=clamp((r.introDuration-r.intro)/1.0,0,1);introY=-(1-journeyEase(a))*h*.8;spin=(1-journeyEase(a))*Math.PI*.3;glow(f.x,f.y-h*.5+introY,60*r.unit,'#d8c1ff29');}
  ellipse(f.x,r.ground+3,h*.29,h*.05,'#09102277');ctx.save();ctx.translate(j.x,j.foot+introY);ctx.rotate(j.tilt+spin);ctx.scale(j.size,j.size);ctx.globalAlpha=j.alpha*(f.inv>0?.74+Math.sin(r.elapsed*38)*.2:1);
  const morphIn=r.intro>0?journeyEase(clamp((r.introDuration-r.intro-.12)/.72,0,1)):1,morphOut=state==='transition'&&transition?.modeExit?1-journeyEase((transition.age/transition.duration-.1)/.4):1,costume=art[hero]?.ready?morphIn*morphOut:0;
  if(costume<1){ctx.save();ctx.globalAlpha*=1-costume;HeroSprites.draw(0,0,hero,f.face,{size:h/78,ground:f.y>=r.ground-.1,moving:true,steering:true,idleTime:0,vx:f.vx||f.face,vy:f.vy,phase:f.walk,attack:true,turn:f.face,clock:r.elapsed});ctx.restore();}
  if(costume>0){ctx.save();ctx.globalAlpha*=costume;drawAtlas(hero,f,h,0,0);ctx.restore();}
  if(f.guard){const fresh=f.guardAge<.17;ctx.strokeStyle=fresh?'#b8fff1':'#d3e8ff94';ctx.lineWidth=fresh?3:1.7;ctx.beginPath();ctx.ellipse(f.face*h*.29,-h*.52,h*.14,h*.36,0,-Math.PI*.5,Math.PI*.5);ctx.stroke();}
  if(f.counter>0){ctx.globalAlpha*=.45;glow(0,-h*.5,h*.7,'#b3ffe52e');}ctx.restore();
 }
 function drawProjectiles(){for(const q of r.projectiles){ctx.save();ctx.translate(q.x,q.y);ctx.rotate(q.angle);if(q.type==='web'){if(window.FightEffects?.drawWeb){ctx.restore();FightEffects.drawWeb({...q,r:q.radius},r.elapsed);continue;}ctx.strokeStyle=q.owner==='p'?'#b8ffde':'#dbe7ff';ctx.lineWidth=1.3;const rad=q.radius;for(let i=0;i<6;i++){const a=i*tau/6;line(0,0,Math.cos(a)*rad,Math.sin(a)*rad,ctx.strokeStyle,1.3);}for(let k=1;k<3;k++){ctx.beginPath();ctx.arc(0,0,rad*k/2,0,tau);ctx.stroke();}}else{if(window.FightEffects?.drawShuriken){ctx.restore();FightEffects.drawShuriken({...q,r:q.radius},r.elapsed);continue;}glow(0,0,q.radius*2.4,'#b1ff722c');ctx.fillStyle=q.owner==='p'?'#c9ffe2':'#b1ed73';ctx.strokeStyle='#ebffd0';ctx.lineWidth=1;ctx.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4,rad=q.radius*(i%2?.30:1);if(i)ctx.lineTo(Math.cos(a)*rad,Math.sin(a)*rad);else ctx.moveTo(Math.cos(a)*rad,Math.sin(a)*rad);}ctx.closePath();ctx.fill();ctx.stroke();circle(0,0,q.radius*.19,'#34491b');}ctx.restore();}
  if(r.tether){const p=r.p,e=r.e,a=r.tether.age;ctx.strokeStyle='#dae9ff';ctx.lineWidth=1.2;for(let i=-1;i<=1;i++){ctx.beginPath();ctx.moveTo(e.x+e.face*fighterHeight(e)*.36,e.y-fighterHeight(e)*.60);ctx.quadraticCurveTo((e.x+p.x)/2,(e.y+p.y)/2-r.height*.55+Math.sin(a*17+i)*r.height*.018,p.x+i*4*r.unit,p.y-r.height*.52);ctx.stroke();}ctx.strokeStyle='#d9eaff88';for(let i=0;i<4;i++){ctx.beginPath();ctx.ellipse(p.x,p.y-r.height*(.26+i*.17),r.height*.22,r.height*.055,-.17,0,tau);ctx.stroke();}const y=clamp(p.y-r.height*1.2,r.top+42,r.ground-r.height);ctx.font=`bold ${clamp(r.w/35,11,15)}px system-ui`;ctx.textAlign='center';ctx.fillStyle='#e3efff';const label='TAP PUNCH / KICK TO CUT',labelHalf=ctx.measureText(label).width*.5+8;ctx.fillText(label,clamp(p.x,labelHalf,r.w-labelHalf),y);for(let i=0;i<r.tether.required;i++)circle(p.x+(i-1)*11,y+13,3.5,i<r.tether.breaks?'#d9ffff':'#667b9e');}
 }
 function meters(){const y=r.top+7,w=Math.min(r.w*.31,270),x=14,name=r.encounter==='destroyer'?'THE DESTROYER':'SPIDER NINJA';ctx.font=`bold ${clamp(r.w/38,9,12)}px system-ui`;ctx.fillStyle='#e4d3ee';ctx.textAlign='left';ctx.fillText(hero==='sun'?'SHAOLIN SUN':'KARATE MOON',x,y);ctx.textAlign='right';ctx.fillText(name,r.w-x,y);for(const [xx,f,color] of [[x,r.p,hero==='sun'?'#ebce99':'#cec2ef'],[r.w-x-w,r.e,r.encounter==='destroyer'?'#b9e394':'#b7a0d6']]){rounded(xx,y+8,w,7,3,'#c8bce82c');rounded(xx,y+8,w*f.hp/100,7,3,color);ctx.strokeStyle='#d2c9e845';ctx.lineWidth=.6;ctx.beginPath();ctx.roundRect(xx,y+8,w,7,3);ctx.stroke();}ctx.textAlign='center';ctx.fillStyle='#e8e1e9';ctx.fillText(`${Math.ceil(r.timer)}`,r.w/2,y+6);ctx.font=`${clamp(r.w/44,9,12)}px system-ui`;ctx.fillText(`${'●'.repeat(r.wins)}${'○'.repeat(2-r.wins)}  R${r.round}/2`,r.w/2,y+22);
  if(r.p.comboLife>0&&r.comboDisplay>1){ctx.textAlign='left';ctx.font=`bold ${clamp(r.w/32,12,19)}px system-ui`;ctx.fillStyle='#f3dfb6';ctx.fillText(`${r.comboDisplay} HIT COMBO`,x,y+41);}
 }
 function telegraph(){const f=r.e;if(f.windup<=0&&f.evade<=0)return;const names={backstep:'BACKSTEP · READY TO DODGE',punch:'FOUR FISTS · GUARD',kick:'SIDE KICK · GUARD / JUMP',leap:'LEAP KICK · STEP BACK',web:'WEB PULL · JUMP / GUARD',shuriken:r.encounter==='destroyer'&&r.round===2?'TWIN STARS · JUMP / GUARD':'GREEN STAR · JUMP / GUARD'},text=names[f.next],size=clamp(r.w/34,10,13);ctx.font=`bold ${size}px system-ui`;ctx.textAlign='center';const width=Math.min(r.w-18,ctx.measureText(text).width+18),x=clamp(f.x,width*.5+7,r.w-width*.5-7),y=r.encounter==='destroyer'?r.top+51:clamp(f.y-fighterHeight(f)*1.14,r.top+49,r.ground-r.height*.8);rounded(x-width/2,y-size-6,width,size+13,6,'#101526de');ctx.fillStyle=f.next==='web'?'#d4e9ff':'#dafaaf';ctx.fillText(text,x,y);
 }
 function compactCaption(title,detail,d,cue=false){const w=cue?110:Math.min(600,d.w-22),h=r.h-r.top<260?23:31,y=r.top+30,cx=cue?clamp(r.p.x,w*.5+6,r.w-w*.5-6):d.w*.5;rounded(cx-w/2,y,w,h,7,'#091322e8');ctx.strokeStyle='#c4cfe660';ctx.lineWidth=.8;ctx.beginPath();ctx.roundRect(cx-w/2,y,w,h,7);ctx.stroke();ctx.textAlign='center';ctx.font=`bold ${clamp(d.w/31,11,17)}px system-ui`;ctx.fillStyle='#f2e6cd';ctx.fillText(title,cx,y+h*.70);if(detail){ctx.font=`${clamp(d.w/40,8.5,11)}px system-ui`;ctx.fillStyle='#101426';ctx.fillRect(0,r.h-21,r.w,21);ctx.fillStyle='#d5e2ed';ctx.fillText(detail,d.w/2,r.h-8);}}
 function render(){if(!r)return;const d={...ModeFX.begin(),ground:r.ground,height:r.height};ctx.save();if(r.shake>0)ctx.translate(Math.sin(r.elapsed*66)*r.shake*.5,Math.cos(r.elapsed*72)*r.shake*.3);if(r.encounter==='destroyer'){destroyedScenery(d);window.RescueStory?.drawDuelCage?.(d,r.elapsed);}else scenery(d);ninja(r.e);heroFighter(r.p);drawProjectiles();for(const e of r.effects){ctx.globalAlpha=clamp(e.life/.5,0,1);star(e.x,e.y,2.2*r.unit,e.color);}ctx.globalAlpha=1;ctx.textAlign='center';ctx.font=`bold ${clamp(14*r.unit,11,19)}px system-ui`;for(const t of r.texts){ctx.globalAlpha=clamp(t.life/.18,0,1);ctx.fillStyle=t.color;ctx.fillText(t.text,clamp(t.x,60,r.w-60),clamp(t.y,r.top+47,r.ground));}ctx.globalAlpha=1;telegraph();ctx.restore();meters();if(r.flash>0){ctx.fillStyle=`rgba(178,240,238,${r.flash*.5})`;ctx.fillRect(0,r.top,r.w,r.h-r.top);}ctx.fillStyle='#ccd0df';ctx.font=`${clamp(r.w/38,9,11)}px system-ui`;ctx.textAlign='center';ctx.fillText(matchMedia('(pointer:coarse)').matches||innerWidth<700?'PUNCH → KICK combo · tap GUARD to parry':'J PUNCH · K KICK · SPACE JUMP · L GUARD  |  PUNCH → KICK combo',r.w/2,r.h-9);
  if(r.intro>0){const last=r.intro<.62,brief=r.h-r.top<260||r.introDuration-r.intro>1.05,title=last?'FIGHT!':`${r.encounter==='destroyer'?'FINAL SPIDER DUEL':'WORLD 1 BOSS DUEL'} · ROUND ${r.round} / 2`,detail=last?'':r.encounter==='destroyer'?(r.round===1?'The Destroyer rises into its fighting form. Jump or guard the web; tap to cut it if caught. Win both rounds to free your friend.':'One round remains. Twin green stars and leaping kicks. Counter after an attack; PUNCH → KICK makes a combo.'):(r.round===1?'PUNCH → KICK makes a combo. Hold GUARD; tap it just before a hit to parry. JUMP for an aerial kick.':'The spider adds webs and stars. Watch the warning, dodge or guard, then counter.');if(brief){const age=r.introDuration-r.intro;if(last)compactCaption(title,'',d,true);else if(age<1.4){ctx.save();ctx.globalAlpha*=1-journeyEase(clamp((age-1.05)/.35,0,1));compactCaption(title,r.encounter==='destroyer'?'JUMP / GUARD THE WEB · TAP TO CUT IF CAUGHT':'PUNCH → KICK COMBO · HOLD GUARD · JUMP TO DODGE',d);ctx.restore();}}else ModeFX.caption(title,detail,d,Math.min(1,r.intro/.15));}
  if(r.between>0){const title=r.result==='win'?(r.wins===2?(r.encounter==='destroyer'?'THE DESTROYER DEFEATED':'SPIDER NINJA DEFEATED'):'K.O. · ROUND 1 WON'):(r.timer<=0?'TIME UP · TRY AGAIN':'ROUND LOST · TRY AGAIN'),detail=r.result==='win'?(r.wins===2?(r.encounter==='destroyer'?'Both rounds won. The cage is unguarded — go and free your friend.':'WORLD 1 COMPLETE · Next: the Weeping Grotto.'):'One round remains. Your opponent changes its fighting style.'):'The same round restarts. Guard the warning, then strike during recovery.';if(r.h-r.top<260)compactCaption(title,r.result==='win'?(r.wins===2?r.encounter==='destroyer'?'2 K.O. WINS · FREE YOUR FRIEND':'WORLD 1 COMPLETE · NEXT WORLD': 'NEXT: ROUND 2 / 2'):'SAME ROUND RESTARTS',d);else ModeFX.caption(title,detail,d);}ModeFX.end();
 }
 function hud(){return r?`${r.encounter==='destroyer'?'FINAL SPIDER DUEL':'WORLD 1 BOSS DUEL'} · ${r.round}/2\n✦ ${score} · ${r.wins}/2 K.O. ROUNDS WON`:'';}
 function snapshot(){return r?{encounter:r.encounter,destination:{...r.destination},round:r.round,wins:r.wins,intro:r.intro,timer:r.timer,between:r.between,result:r.result,p:{...r.p,attackPhase:attackPhase(r.p)},e:{...r.e,attackPhase:attackPhase(r.e)},bounds:{w:r.w,h:r.h,top:r.top,ground:r.ground,height:r.height},projectiles:r.projectiles.map(q=>({...q})),tether:r.tether?{...r.tether}:null,combo:r.comboDisplay,stats:{...r.stats}}:null;}
 return {start,resize,press,update,render,hud,snapshot,loadingPromise,get ready(){return Object.values(art).every(a=>a.ready);}};
})();
